### ISSUE TITLE
Wireframes for UI

### ISSUE THREAD

**Issue by MATTALUI** [MATTALUI/cse341-team02#3]
We'll need UI designs for
- [x] Splash page for not logged in user (`/`)
- [x] Dashboard for a logged in user (`/`)
- [x] Sign in page (`/auth/login`)
- [x] Sign Up page (`/auth/signup`)
- [x] Groups index page, list for all groups in the ward (`/groups`)
- [x] Page for specific group's information and all of the messages in that group (`/groups/:groupId`)
- [x] Page for creating a new group (`/groups/new`)
- [x] Page for editing a group (`/groups/:groupId/edit`)
- [x] Page for subscribing/editing subscription preferences(`/groups/:groupId/preferences`)
- [x] Page for posting a new announcement/message to a group (`/groups/:groupId/messages/new`)
- [x] Page for viewing a specific message (`/groups/:groupId/messages/:messageId`)
- [x] 404 page
- [x] 500 page

**Comment by jesuisnicolas** [comment]
Here's the link to the wireframes.

https://www.figma.com/file/N9CbfHhn6Bi6Ikm8vXtU8G/Litzen?node-id=24%3A241
