### ISSUE TITLE
Choose Color scheme

### ISSUE THREAD

**Issue by MATTALUI** [MATTALUI/cse341-team02#4]
We can use [Coolors](https://coolors.co/generate) to choose a color scheme for the application. We'll need

- [x] Primary Color
- [x] Primary Color accent
- [x] Secondary Color
- [x] Secondary Color  Accent
- [x] Light
- [x] Dark

**Comment by JessD1234** [comment]
https://coolors.co/012622-00524b-009fb7-007981-fed766-f5b400-ffffff
